### ISSUE TITLE
Remove comment in output css minify

### ISSUE THREAD

**Issue by Mudza09** [webyom/gulp-minifier#12]
Hi, how can I remove comment in css minify, there no description how to do this in your readme

**Comment by webyom** [comment]
@Mudza09 comments in css are removed by default, except copyright comments. Refer to clean-css document for detail https://github.com/jakubpawlowicz/clean-css

**Comment by mudza09** [comment]
thanks for the answer, i have one more question how to remove javascript comment? can you show me how to do it?

**Comment by mudza09** [comment]
forget it, I've figured it out, thank you very much
