### ISSUE TITLE
ReferenceError: includeExtNameMap is not defined

### ISSUE THREAD

**Issue by playground** [webyom/gulp-minifier#3]
/Users/git_repo/node_modules/gulp-minifier/lib/index.js:65
    if ((extname === '.js' || extname === '.css' || extname === '.html') || includeExtNameMap[extname]) {

Resolve by moving var includeExtNameMap; out of module.exports function.

**Comment by webyom** [comment]
fixed in version 0.1.4

**Comment by playground** [comment]
Thanks for fixing this.

Quick question, is there a way to specify the extension name format for minified output files?
something like this ".min.js".

**Comment by webyom** [comment]
@playground you can use gulp-rename to do this.
