### ISSUE TITLE
Angular controller injection  problem

### ISSUE THREAD

**Issue by qubaish-techverx** [webyom/gulp-minifier#6]
I am facing problem which is some of my angular controller minify correctly and some of them not,
like some controller 
`   function ProductTilesController($rootScope,$scope,$window,$timeout, $filter, $http, $state, $mdSidenav, $mdDialog, triSettings, $location, products, pricing, $q) {
`
retain there params and some of them behaving like this
`function o(o,l,e,r,n,c,i,t,a,s,u)` 
do you have any idea why this is happening.

**Comment by webyom** [comment]
@qubaish-techverx we use `uglify-js@2.8.20` for JS minify, could you try using it directly to see whether the problem is still exist.
